# Import libraries

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy  as np
from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator, SimpleImputer

# import dataset

In [6]:
df =pd.read_csv('train.csv', usecols=['Age','Fare','Survived'])

In [7]:
df

     Survived   Age     Fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
886         0  27.0  13.0000
887         1  19.0  30.0000
888         0   NaN  23.4500
889         1  26.0  30.0000
890         0  32.0   7.7500

[891 rows x 3 columns]

In [8]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

# Create X & y

In [11]:
X  =df.drop(columns=['Survived'])
y =df['Survived']

# Train & Test split

In [12]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [13]:
X_train

      Age      Fare
30   40.0   27.7208
10    4.0   16.7000
873  47.0    9.0000
182   9.0   31.3875
876  20.0    9.8458
..    ...       ...
534  30.0    8.6625
584   NaN    8.7125
493  71.0   49.5042
527   NaN  221.7792
168   NaN   25.9250

[712 rows x 2 columns]

In [14]:
X_test

      Age     Fare
707  42.0  26.2875
37   21.0   8.0500
615  24.0  65.0000
169  28.0  56.4958
68   17.0   7.9250
..    ...      ...
89   24.0   8.0500
80   22.0   9.0000
846   NaN  69.5500
870  26.0   7.8958
251  29.0  10.4625

[179 rows x 2 columns]

In [15]:
y_test

707    1
37     0
615    1
169    0
68     1
      ..
89     0
80     0
846    0
870    0
251    0
Name: Survived, Length: 179, dtype: int64

In [16]:
y_train

30     0
10     1
873    0
182    0
876    0
      ..
534    0
584    0
493    0
527    0
168    0
Name: Survived, Length: 712, dtype: int64

# Review Without " Missing Indicator Method" Technique

si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf  = si.transform(X_test)

X_test_trf

# Call Logistic Regression

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
clf = LogisticRegression()
clf.fit(X_train_trf,y_train)
y_pred = clf.predict(X_test_trf)

In [22]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6145251396648045

# Define Missing Indicator

In [23]:
mi = MissingIndicator()
mi.fit(X_train)

MissingIndicator()

mi.features_

array([0], dtype=int64)

# Transform:train Missing

In [24]:
X_train_missing = mi.transform(X_train)
X_train_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True]])

# Transform: Test Missing

In [25]:
X_test_missing = mi.transform(X_test)
X_test_missing

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False]])

# Create New Column

In [26]:
X_train['Age_NA'] =X_train_missing
X_train

      Age      Fare  Age_NA
30   40.0   27.7208   False
10    4.0   16.7000   False
873  47.0    9.0000   False
182   9.0   31.3875   False
876  20.0    9.8458   False
..    ...       ...     ...
534  30.0    8.6625   False
584   NaN    8.7125    True
493  71.0   49.5042   False
527   NaN  221.7792    True
168   NaN   25.9250    True

[712 rows x 3 columns]

# Create New Column

In [27]:
X_test['Age_NA'] =X_test_missing
X_test

      Age     Fare  Age_NA
707  42.0  26.2875   False
37   21.0   8.0500   False
615  24.0  65.0000   False
169  28.0  56.4958   False
68   17.0   7.9250   False
..    ...      ...     ...
89   24.0   8.0500   False
80   22.0   9.0000   False
846   NaN  69.5500    True
870  26.0   7.8958   False
251  29.0  10.4625   False

[179 rows x 3 columns]

# Writing code again and check Accuracy

In [29]:
si = SimpleImputer()
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2  = si.transform(X_test)

X_test_trf2

array([[ 42.        ,  26.2875    ,   0.        ],
       [ 21.        ,   8.05      ,   0.        ],
       [ 24.        ,  65.        ,   0.        ],
       [ 28.        ,  56.4958    ,   0.        ],
       [ 17.        ,   7.925     ,   0.        ],
       [ 30.        ,   7.8958    ,   0.        ],
       [ 80.        ,  30.        ,   0.        ],
       [ 25.        ,   7.25      ,   0.        ],
       [ 50.        , 133.65      ,   0.        ],
       [ 25.        ,  26.        ,   0.        ],
       [ 35.        ,  26.        ,   0.        ],
       [ 35.        ,  90.        ,   0.        ],
       [ 55.        ,  16.        ,   0.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 29.78590426,  56.4958    ,   1.        ],
       [ 19.        ,   7.8542    ,   0.        ],
       [ 29.78590426,  15.2458    ,   1.        ],
       [ 49.        ,   0.        ,   0.        ],
       [ 18.        ,  14.4542    ,   0.        ],
       [ 65.        ,   7.75      ,   0.        ],
       [ 18.        , 108.9       ,   0.        ],
       [ 29.78590426,  22.3583    ,   1.        ],
       [ 16.        ,  18.        ,   0.        ],
       [ 21.        ,   9.825     ,   0.        ],
       [ 19.        ,   6.75      ,   0.        ],
       [  1.        ,  11.1333    ,   0.        ],
       [ 50.        ,  10.5       ,   0.        ],
       [ 37.        ,  53.1       ,   0.        ],
       [ 28.        ,   9.5       ,   0.        ],
       [ 54.        ,  14.        ,   0.        ],
       [ 20.        ,   7.925     ,   0.        ],
       [ 36.        ,   0.        ,   0.        ],
       [  6.        ,  31.275     ,   0.        ],
       [ 29.78590426,  50.        ,   1.        ],
       [ 40.        ,  31.        ,   0.        ],
       [ 26.        ,  16.1       ,   0.        ],
       [ 30.        ,  93.5       ,   0.        ],
       [  1.        ,  46.9       ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 35.        ,  10.5       ,   0.        ],
       [ 38.        ,   7.05      ,   0.        ],
       [ 44.        ,  16.1       ,   0.        ],
       [ 22.        ,   7.75      ,   0.        ],
       [ 18.        ,   6.4958    ,   0.        ],
       [ 21.        ,   8.4333    ,   0.        ],
       [ 29.78590426, 227.525     ,   1.        ],
       [ 21.        ,  77.9583    ,   0.        ],
       [ 29.78590426,   8.6625    ,   1.        ],
       [ 22.        ,   7.225     ,   0.        ],
       [ 27.        ,  10.5       ,   0.        ],
       [ 29.78590426,   8.05      ,   1.        ],
       [ 51.        ,  26.55      ,   0.        ],
       [ 28.        ,  33.        ,   0.        ],
       [ 47.        ,  38.5       ,   0.        ],
       [ 32.        ,  10.5       ,   0.        ],
       [ 48.        ,  52.        ,   0.        ],
       [ 10.        ,  24.15      ,   0.        ],
       [ 21.        ,   8.6625    ,   0.        ],
       [ 51.        ,   7.0542    ,   0.        ],
       [ 32.        ,   7.925     ,   0.        ],
       [ 42.        ,  13.        ,   0.        ],
       [  2.        ,  26.        ,   0.        ],
       [ 35.        ,   8.05      ,   0.        ],
       [ 29.78590426,   7.25      ,   1.        ],
       [  2.        ,  10.4625    ,   0.        ],
       [ 33.        ,   9.5       ,   0.        ],
       [ 48.        ,  25.9292    ,   0.        ],
       [ 55.        ,  30.5       ,   0.        ],
       [  1.        ,  39.6875    ,   0.        ],
       [ 17.        ,   7.0542    ,   0.        ],
       [ 24.        ,  15.85      ,   0.        ],
       [ 74.        ,   7.775     ,   0.        ],
       [ 29.78590426,  24.15      ,   1.        ],
       [ 28.        ,   7.7958    ,   0.        ],
       [ 26.        ,   7.8542    ,   0.        ],
       [  1.        ,  39.        ,   0.        ],
       [ 18.        ,   8.05      ,   0.        ],
       [  3.        ,  26.        ,   0.        ],
       [ 48.        ,  39.6       ,   0.        ],
       [ 32.        ,  56.4958    ,   0.        ],
       [ 19.        ,  91.0792    ,   0.        ],
       [ 29.78590426,  42.4       ,   1.        ],
       [ 70.        ,  10.5       ,   0.        ],
       [ 34.        ,  26.        ,   0.        ],
       [ 39.        , 110.8833    ,   0.        ],
       [ 17.        ,  10.5       ,   0.        ],
       [ 38.        ,   8.6625    ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 30.        ,  21.        ,   0.        ],
       [ 28.        ,  13.        ,   0.        ],
       [ 29.78590426,   7.725     ,   1.        ],
       [ 19.        ,   8.1583    ,   0.        ],
       [ 29.        ,   7.75      ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 44.        ,   7.925     ,   0.        ],
       [ 22.        ,  41.5792    ,   0.        ],
       [ 21.        ,  34.375     ,   0.        ],
       [ 41.        ,  19.5       ,   0.        ],
       [ 29.78590426,   7.225     ,   1.        ],
       [ 25.        ,  55.4417    ,   0.        ],
       [  0.92      , 151.55      ,   0.        ],
       [ 44.        ,  26.        ,   0.        ],
       [ 19.        ,  26.        ,   0.        ],
       [ 30.        ,  56.9292    ,   0.        ],
       [ 20.        ,   9.5       ,   0.        ],
       [  5.        ,  12.475     ,   0.        ],
       [  4.        ,  39.        ,   0.        ],
       [ 29.78590426,  16.1       ,   1.        ],
       [ 38.        ,   0.        ,   0.        ],
       [ 28.        ,  22.525     ,   0.        ],
       [ 29.78590426,  30.        ,   1.        ],
       [ 29.        ,   7.775     ,   0.        ],
       [ 49.        ,  89.1042    ,   0.        ],
       [ 19.        ,  14.5       ,   0.        ],
       [ 18.        , 262.375     ,   0.        ],
       [ 31.        ,  26.25      ,   0.        ],
       [ 27.        ,   7.7958    ,   0.        ],
       [ 36.        , 120.        ,   0.        ],
       [  8.        ,  36.75      ,   0.        ],
       [  2.        ,  21.075     ,   0.        ],
       [ 63.        ,  77.9583    ,   0.        ],
       [ 31.        ,   7.75      ,   0.        ],
       [ 29.78590426,   0.        ,   1.        ],
       [ 25.        ,  13.        ,   0.        ],
       [ 20.5       ,   7.25      ,   0.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 64.        , 263.        ,   0.        ],
       [ 19.        ,  26.        ,   0.        ],
       [ 18.        ,   7.775     ,   0.        ],
       [ 29.78590426,   0.        ,   1.        ],
       [ 29.78590426,   7.8958    ,   1.        ],
       [ 11.        ,  18.7875    ,   0.        ],
       [ 15.        ,  14.4542    ,   0.        ],
       [ 22.        ,  55.        ,   0.        ],
       [ 50.        ,  13.        ,   0.        ],
       [ 28.        ,  14.4       ,   0.        ],
       [ 39.        ,  13.        ,   0.        ],
       [ 29.78590426,   8.05      ,   1.        ],
       [ 39.        ,   7.925     ,   0.        ],
       [ 24.        ,  16.1       ,   0.        ],
       [ 23.        ,   7.925     ,   0.        ],
       [ 17.        ,  57.        ,   0.        ],
       [ 44.        ,  26.        ,   0.        ],
       [ 23.        ,  13.7917    ,   0.        ],
       [ 29.78590426,  26.55      ,   1.        ],
       [ 52.        ,  78.2667    ,   0.        ],
       [ 24.5       ,   8.05      ,   0.        ],
       [ 55.5       ,   8.05      ,   0.        ],
       [ 18.        ,   7.7958    ,   0.        ],
       [ 18.        ,  13.        ,   0.        ],
       [ 45.        ,  83.475     ,   0.        ],
       [ 31.        ,  18.        ,   0.        ],
       [ 30.5       ,   8.05      ,   0.        ],
       [ 42.        ,   8.4042    ,   0.        ],
       [ 29.78590426,   7.75      ,   1.        ],
       [ 36.        ,   7.4958    ,   0.        ],
       [ 34.        ,  26.55      ,   0.        ],
       [ 54.        ,  78.2667    ,   0.        ],
       [ 15.        ,   8.0292    ,   0.        ],
       [ 25.        ,   7.775     ,   0.        ],
       [ 26.        ,  30.        ,   0.        ],
       [ 29.78590426,   8.1125    ,   1.        ],
       [ 19.        ,   8.05      ,   0.        ],
       [ 29.        ,   7.8958    ,   0.        ],
       [ 19.        ,  30.        ,   0.        ],
       [ 33.        ,  90.        ,   0.        ],
       [ 36.        ,  24.15      ,   0.        ],
       [ 29.78590426,   7.775     ,   1.        ],
       [ 35.        , 512.3292    ,   0.        ],
       [ 22.        ,   7.25      ,   0.        ],
       [ 29.78590426,  16.1       ,   1.        ],
       [ 18.        ,   7.4958    ,   0.        ],
       [ 28.        ,  26.        ,   0.        ],
       [ 22.        ,   7.25      ,   0.        ],
       [ 24.        ,   8.05      ,   0.        ],
       [ 22.        ,   9.        ,   0.        ],
       [ 29.78590426,  69.55      ,   1.        ],
       [ 26.        ,   7.8958    ,   0.        ],
       [ 29.        ,  10.4625    ,   0.        ]])

In [32]:
clf = LogisticRegression()
clf.fit(X_train_trf2,y_train)
y_pred = clf.predict(X_test_trf2)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6312849162011173