### start coding

In [4]:
import numpy as np
!pip install pandas
import pandas as pd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\hpcod\appdata\roaming\python\python311\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (1.24.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2022.7)
Requirement already satisfied: tzdata>=2022.7 in c:\users\hpcod\appdata\roaming\python\python311\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [5]:
df = pd.read_csv('customer.csv')

In [6]:
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [7]:
df.sample(10)

    age  gender   review education purchased
11   74    Male     Good        UG       Yes
18   19    Male     Good    School        No
39   76    Male     Poor        PG        No
49   25  Female     Good        UG        No
31   22  Female     Poor    School       Yes
0    30  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
10   98  Female     Good        UG       Yes
1    68  Female     Poor        UG        No

In [8]:
df.shape

(50, 5)

### Eliminate  Unnecessary  Columns

In [9]:
df = df.iloc[:,2:]

In [10]:
df

     review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [20]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

### Import_OrdinalEncoding

In [14]:
from sklearn.preprocessing import OrdinalEncoder

In [21]:
x_train

     review education
41     Good        PG
17     Poor        UG
33     Good        PG
23     Good    School
25     Good    School
16     Poor        UG
24  Average        PG
9      Good        UG
40     Good    School
45     Poor        PG
35     Poor    School
28     Poor    School
46     Poor        PG
38     Good    School
47     Good        PG
12     Poor    School
39     Poor        PG
36     Good        UG
10     Good        UG
15     Poor        UG
14     Poor        PG
18     Good    School
20  Average    School
7      Poor    School
19     Poor        PG
6      Good    School
22     Poor        PG
21  Average        PG
49     Good        UG
3      Good        PG
26     Poor        PG
5   Average    School
37  Average        PG
30  Average        UG
13  Average    School
11     Good        UG
42     Good        PG
2      Good        PG
1      Poor        UG
31     Poor    School

### Define Categories

oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(x_train)

### Transform Ordinal Encoding

In [28]:
x_train = oe.transform(x_train)
x_test = oe.transform(x_test)

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

In [29]:
x_train

array([[2., 2.],
       [0., 1.],
       [2., 2.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [1., 2.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [0., 0.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [0., 1.],
       [0., 2.],
       [2., 0.],
       [1., 0.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 2.],
       [2., 2.],
       [0., 1.],
       [0., 0.]])

In [31]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

### Label Encoding

In [34]:
from sklearn.preprocessing import LabelEncoder

In [35]:
le = LabelEncoder()

In [38]:
le.fit(y_train)

LabelEncoder()

In [39]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [40]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [41]:
y_train

array([1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1])